### ISSUE TITLE
Possible to trigger zones?

### ISSUE THREAD

**Issue by plouj** [BioSehnsucht/pyelk#4]
This question may be a bit more general than just this Python API, but I'm wondering if it's possible to create a "virtual" zone in the Elk that isn't actually connected to the panel directly and then use a serial interface such as PyElk to tell the Elk panel that this zone has been triggered?

**Comment by lmamakos** [comment]
The M1 Elk serial protocol has a "Zone Trigger" command that works like this:

```
4.41 ZoneTrigger(zt)

This command allows automation equipment to momentarily open and violate any
zone definition from zone type 1, Burglar Entry/Exit up to but not including type 26, 
momentary keyswitch zone. This command is available in M1 Version 4.5.23, 
5.1.23 and above.

  4.41.1 ZoneTrigger(zt)
    09 – Length as ASCII hex
    zt – Get command for zone trigger violation
    ZZZ – Zone number 001 to 208 as 3 ASCII decimal characters 00 – future use
    CC – Checksum
        Example: 09zt12300B3 Zone 123 momentarily violate zone.
```

Seems like maybe this could do it.  The question is if you can somehow figure out how to define a zone that doesn't have hardware behind it.

**Comment by BioSehnsucht** [comment]
I think you can also connect an output to a zone to trigger the zone, but that requires actual hardware available (both an output and a zone physically present) to do so.

**Comment by BioSehnsucht** [comment]
This is abandoned. Please use https://github.com/gwww/elkm1 / https://pypi.org/project/elkm1-lib/
