### ISSUE TITLE
Access to zone Type?

### ISSUE THREAD

**Issue by jimboca** [BioSehnsucht/pyelk#6]
In ElkRP there is a Zone Type:
0 = EOL Hardwire / Wireless
1 = Normally Closed
2 = Normally Open
3 = EOL Supervised on Short
4 = EOL Supervised on Open

Are these available in pyelk?

**Comment by BioSehnsucht** [comment]
This is abandoned. Please use https://github.com/gwww/elkm1 / https://pypi.org/project/elkm1-lib/
